#!/usr/bin/env ruby

require 'triglav/agent/vertica'
Triglav::Agent::Configuration.configure do |config|
  # config.cli_class = Triglav::Agent::Vertica::CLI
  # config.setting_class = Triglav::Agent::Vertica::Setting
  config.worker_module = Triglav::Agent::Vertica::Worker
end
Triglav::Agent::Configuration.cli_class.new.run
